version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-quote-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - discord-bot-logs:/app/logs
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

volumes:
  discord-bot-logs: